name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Push dist to repo
        run: |
          git config user.email "dansonnjihia0100@gmail.com"
          git config user.name "wizzdan"
          git add dist/ -f
          git commit -m "Add build dist" || echo "No changes"
          git push
